feat(format): add effector-format
effector/patronum pull request #142
Opened 2021-05-18 11:02 UTC by blednaya-luna

### Description

### Checklist for a new method

- [ ] Create directory for new method in root in `param-case`
- [ ] Place code to `{method-name}/index.js` in CommonJS export in `camelCase` named export
- [ ] Add types to `{method-name}/index.d.ts`
- [ ] Add tests to `{method-name}/{method-name}.test.ts`
- [ ] Add **fork** tests to `{method-name}/{method-name}.fork.test.ts`
- [ ] Add **type** tests to `test-typings/{method-name}.ts`
  - Use `// @ts-expect-error` to mark expected type error
  - `import { expectType } from 'tsd'` to check expected return type
- [ ] Add documentation in `{method-name}/reade.md`
  - Add header `Patronum/MethodName`
  - Add section with overloads, if have
  - Add `Motivation`, `Formulae`, `Arguments` and `Return` sections for each overload
  - Add useful examples in `Example` section for each overload
- [ ] Add section to `README.md` in root
  - Add method to table of contents `- [MethodName](#methodname)`
  - Add section `## [MethodName](/method-name 'Documentation')`
  - With summary and simple example

2021-05-18 11:18 UTC, sergeysova requested changes

2021-05-18 11:18 UTC, sergeysova commented on format/format.fork.test.ts
> +  `);
But you don't test that `_$result` contains actual value

2021-05-18 11:18 UTC, sergeysova commented on format/format.fork.test.ts
> +  const _$result = format`My name is ${$name}`;
The same here

2021-05-18 11:18 UTC, sergeysova commented on format/format.fork.test.ts
> +  `);
You can

```js
expect(scope.getState($result)).
```

2021-05-18 11:18 UTC, sergeysova commented on format/index.d.ts
> +): Store<string>;
```suggestion
export function format<T extends Array<Store<any>>>(
  string: TemplateStringsArray,
  ...stores: T,
): Store<string>;
```

[Try it](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRtApgGjgYyugQxnVQzgF84AzKCEOAcnSqvRzSgYCguATNgDYF81AK4A7dsAjjq0EEQA8AQTjoAHsXG8AznGVQoBAJ6LS+RQXHGAfHYAUXOHB0wowcQHMAXHAAq6OBCxKjuXjoGRsaYTnAAdAmuGDq+yjEAlL7m6IquYZ42ANw8ODKucARwALy4+EQkHOj2AIzpXKXi5QBG1bWEIY32AERUEBBDbe1l8Pg6ogLwNaNQCjAABgBiY3AAJAgElHtd5Gs8QA)

2021-05-18 11:18 UTC, sergeysova commented on format/format.test.ts
> +});
```suggestion
});

test('latest chunk of string is not lost', () => {
  const fn = jest.fn();
  const changeName = createEvent();
  const changeAge = createEvent();

  const $name = createStore('Mike').on(changeName, () => 'Bob');
  const $age = createStore(28).on(changeAge, () => 30);

  const $result = format`That ${$name} is a ${$age} old`;

  $result.watch(fn);
  expect(fn).toHaveBeenCalledWith('That Mike is a 28');

  changeName();
  changeAge();
  expect(argumentHistory(fn)).toMatchInlineSnapshot(`
    Array [
      "That Mike is a 28 old",
      "That Bob is a 28 old",
      "That Bob is a 30 old",
    ]
  `);
});
```

2021-05-18 11:18 UTC, sergeysova commented on index.js
> +module.exports.format = require('./format').format;
Don't need to do this by yourself, just run `yarn build:methods`

2021-05-18 15:52 UTC, blednaya-luna commented
my english is very bad :( and i don't think what i can fill out documentation correctly

2021-05-27 17:15 UTC, sergeysova approved these changes

2021-05-27 19:08 UTC, AlexandrHoroshih commented on format/index.d.ts
> +export function format<T extends Array<Store<any>>>(
Wouldn't it be better to allow in types not just stores, but primitives too?

Like this:
```ts
const $name = createStore('Bob').on(change, (name) => nameMap.get(name));
const $age = $name.map(name => ageMap.get(name));

const formatted = format`${window.BASE_STRING} ${$name} ${$age}`;
```
It works correctly without typescript:
https://share.effector.dev/EKLxy7A1
so why not support this at types level

Types for that can be [borrowed from `forest`'s types](https://github.com/effector/effector/blob/261007707c52ddd6995fc80e4042e6348a05c58c/src/forest/index.h.ts#L50) 

 Everything else looks cool, nice work

2021-06-19 11:52 UTC, sergeysova approved these changes

2021-06-19 11:53 UTC, sergeysova commented
Thank you!

2021-06-19 11:53 UTC, merged