Add `currentTime` method
effector/patronum pull request #157
Opened 2021-06-23 04:08 UTC by igorkamyshev

### Description

Discussed in #152

### Checklist for a new method

- [ ] Create directory for new method in root in `param-case`
- [ ] Place code to `{method-name}/index.js` in CommonJS export in `camelCase` named export
- [ ] Add types to `{method-name}/index.d.ts`
- [ ] Add tests to `{method-name}/{method-name}.test.ts`
- [ ] Add **fork** tests to `{method-name}/{method-name}.fork.test.ts`
- [ ] Add **type** tests to `test-typings/{method-name}.ts`
  - Use `// @ts-expect-error` to mark expected type error
  - `import { expectType } from 'tsd'` to check expected return type
- [ ] Add documentation in `{method-name}/reade.md`
  - Add header `Patronum/MethodName`
  - Add section with overloads, if have
  - Add `Motivation`, `Formulae`, `Arguments` and `Return` sections for each overload
  - Add useful examples in `Example` section for each overload
- [ ] Add section to `README.md` in root
  - Add method to table of contents `- [MethodName](#methodname)`
  - Add section `## [MethodName](/method-name 'Documentation')`
  - With summary and simple example

2021-06-27 04:39 UTC, igorkamyshev commented
@sergeysova hello. Could you review this PR please?

2021-06-30 12:35 UTC, sergeysova requested changes

2021-06-30 12:35 UTC, sergeysova commented on babel-plugin-factories.json
> +    "patronum/currentTime",
Please, run `yarn build:methods` and commit changes

2021-06-30 12:35 UTC, sergeysova commented on current-time/current-time.test.ts
> +    for (const interval of testIntrevals) {
You can use [`test.each`](https://jestjs.io/docs/api#testeachtablename-fn-timeout) to simplify test:

```suggestion
  test.each([20, 200, 2000])('should use %i interval', (interval) => {
```

2021-06-30 12:35 UTC, sergeysova commented on current-time/index.js
> +function currentTime({ start, stop, interval = 100 }) {
What about adding a `clock` argument?

```ts
const $time = time({ start, stop, clock });

$time.getState() // time at initialize moment

clock() // now, $time changed to moment when clock triggered
```

2021-07-27 11:28 UTC, igorkamyshev commented
So, I'm closing this PR. I'll send another one with `interval` implementation, and then I'll create `time` method based on `interval`. Thanks for review and ideas.

2021-07-27 11:28 UTC, closed without merging