feat: expose timers api
effector/patronum pull request #327
Opened 2024-04-22 23:07 UTC by movpushmov

### Description

### Checklist for a new method

- [ ] Create a directory for the new method in the `src` directory in `param-case`
- [ ] Place the source code to `src/method-name/index.ts` in ESModules export in `camelCase` **named** export
- [ ] Add tests to `src/method-name/method-name.test.ts`
- [ ] Add **fork** tests to `src/method-name/method-name.fork.test.ts`
- [ ] Add **type** tests to `test-typings/method-name.ts`
  - Use `// @ts-expect-error` to mark expected type error
  - `import { expectType } from 'tsd'` to check expected return type
- [ ] Add documentation in `src/method-name/readme.md`
  - Add header `Patronum/MethodName`
  - Add section with overloads, if have
  - Add `Motivation`, `Formulae`, `Arguments` and `Return` sections for each overload
  - Add useful examples in `Example` section for each overload
- [ ] Add section to `README.md` in the repository root
  - Add method to the table of contents into correct category `- [MethodName](#methodname) - description.`
  - Add section `## MethodName`
  - Add `[Method documentation & API](/src/method-name)` into section
  - Add simple example

2024-04-23 16:26 UTC, AlexandrHoroshih approved these changes
Aside from a few nitpicks about the documentation:

Awesome! Great job, thank you 💙

2024-04-23 16:26 UTC, AlexandrHoroshih commented on src/debounce/index.ts
> +    target: spread({
Need to check, that does not lead to `spread` duplicate in the bundle 🤔 

If it does - simplest option would be to just split it into two `sample`, i think

2024-04-23 16:26 UTC, AlexandrHoroshih commented on src/time/readme.md
> +// you can attach() any source of time
I suggest to rephrase a comment a bit, so it is easier to understand, what is going on - something like this

```suggestion
/**
* `timeReader` - is a either `Date.now` or the handler, that was provided via `getNow` in the configuration
*
* In your custom `readNowFx` you can change the way original time reader is used or call your own timer instead
*/
```

Maybe, it actually should just be above of the code example 🤔

2024-05-14 11:08 UTC, sergeysova requested changes

2025-01-06 18:09 UTC, closed without merging